export const LIST_OF_WRAPPED_TOKENS_AND_STABLECOINS = [
  { key: 'ETH', label: 'ETH' },
  { key: 'rsETH', label: 'rsETH' },
  { key: 'DAI', label: 'DAI' },
  { key: 'eUSD', label: 'eUSD' },
  { key: 'EURC', label: 'EURC' },
  { key: 'hyUSD', label: 'hyUSD' },
  { key: 'USDbC', label: 'USDbC' },
  { key: 'USDC', label: 'USDC' },
  { key: 'bsdETH', label: 'bsdETH' },
  { key: 'cbETH', label: 'cbETH' },
  { key: 'ezETH', label: 'ezETH' },
  { key: 'rETH', label: 'rETH' },
  { key: 'weETH', label: 'weETH' },
  { key: 'wstETH', label: 'wstETH' },
  { key: 'wsuperOETHb', label: 'wsuperOETHb' },
  { key: 'tBTC', label: 'tBTC' },
  { key: 'cbBTC', label: 'cbBTC' },
  { key: 'wUSDM', label: 'wUSDM' },
  { key: 'wUSD+', label: 'wUSD+' },
];